# Generated by Django 5.0.6 on 2024-07-29 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_icon', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_instructor', models.CharField(max_length=100)),
                ('course_rating', models.IntegerField(null=True)),
                ('course_duration', models.CharField(max_length=500, null=True)),
                ('course_price', models.IntegerField(null=True)),
                ('course_description', models.CharField(max_length=500)),
                ('course_languages', models.CharField(max_length=300)),
                ('course_discount', models.IntegerField(null=True)),
                ('course_thumbnail', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bywayapp.category')),
            ],
        ),
    ]
