# Generated by Django 5.0.6 on 2024-07-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bywayapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_icon',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
