# Generated by Django 5.0.6 on 2024-07-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bywayapp', '0002_alter_category_cat_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
